# Generated by Django 4.0.5 on 2022-07-03 10:57

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=Core.models.upload_to)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
