# Generated by Django 4.0.5 on 2022-07-03 20:05

import Core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(upload_to=Core.models.upload_to)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_image',
            },
        ),
    ]
