# Generated by Django 4.0.5 on 2022-07-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ('upload_time',)},
        ),
        migrations.AlterModelTable(
            name='imagemodel',
            table='images',
        ),
        migrations.CreateModel(
            name='ImageOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_num', models.IntegerField(blank=True, default=0, null=True)),
                ('operation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ImageOperations', to='Core.imagemodel')),
            ],
            options={
                'db_table': 'image_operations',
                'ordering': ('operation_num',),
            },
        ),
    ]
