# Generated by Django 4.0.5 on 2022-07-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadimagemodel',
            table='uploaded_image',
        ),
    ]
