export const ToolsIndices = {
  MainTool: {
    BasicTools: 0,
    FaceTools: 1,
    BodyTools: 2,
    FilterTools: 3,
  },
  UserTool: {
    CompareTool: 4,
    UndoTool: 5,
    RedoTool: 6,
    ZoomTool: 24,
  },
  SubTools: {
    FlipTool: 7,
    ResizeTool: 8,
    ContrastTool: 9,
    CropTool: 10,
    RotateTool: 11,
    SaturationTool: 12,
    SmileTool: 13,
    EyeColorTool: 14,
    EyeResizeTool: 15,
    NoseResizeTool: 16,
    HairColorTool: 17,
    SmoothFaceTool: 18,
    WhiteTeethTool: 19,
    ColorLipsTool: 20,
    ChangeColorTool: 21,
    GlitchFilter: 22,
    CirclesFilter: 23,
  },
};
